/*
 * This Scala Testsuite was generated by the Gradle 'init' task.
 */
package _lakh_record_generation
import org.junit.runner.RunWith
import org.scalatest.funsuite.AnyFunSuite
import org.scalatestplus.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class AppSuite extends AnyFunSuite {
  test("App runs successfully") {
    assert(services.App != null) // or another test of your choice
  }
}
